Repository AY2223S1-CS2103T-T11-4/tp, pull requests merged in 2022-11, with the labels that each got.

#228 Account for Legacy GitHub usernames
  docs/UserGuide.md
  src/main/java/seedu/masslinkers/model/student/GitHub.java
  src/test/java/seedu/masslinkers/model/student/GitHubTest.java
Labels: bug fix

#240 Update UG Screenshots
  docs/UserGuide.md
  docs/images/UgModAdd.png
  docs/images/UgModAddAfter.png
  docs/images/UgModAddBefore.png
  docs/images/UgModMark.png
  docs/images/UgModMarkAfter.png
  docs/images/UgModMarkBefore.png
  docs/images/UgViewMod.png
  docs/images/UgViewModAfter.png
  docs/images/UgViewModBefore.png
  docs/images/Ui.png
  docs/images/UiBreakDown.png
Labels: documentation

#247 Fix authorship issues
  docs/team/carriezhengjr.md
  src/main/java/seedu/masslinkers/logic/parser/ModCommandParser.java
  src/main/java/seedu/masslinkers/model/student/Mod.java
  src/main/java/seedu/masslinkers/ui/HelpWindow.java
  src/test/java/seedu/masslinkers/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/masslinkers/logic/commands/AddCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/AddInterestCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ClearCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/CommandResultTest.java
  src/test/java/seedu/masslinkers/logic/commands/CommandTestUtil.java
  src/test/java/seedu/masslinkers/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/DeleteInterestCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/EditCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/masslinkers/logic/commands/ExitCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/FindCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/FindInterestCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/HelpCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ListCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ModAddCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ModDeleteCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ModFindCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ModMarkAllCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ModMarkCommandTest.java
  src/test/java/seedu/masslinkers/logic/commands/ModUnmarkCommandTest.java
  src/test/java/seedu/masslinkers/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/masslinkers/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/MassLinkersParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/ModCommandParserTest.java
Labels: documentation

#252 Change bullet points of headings, fix grammar errors
  docs/UserGuide.md
Labels: documentation

#251 Add Future Developments DG alphabetical sort
  docs/DeveloperGuide.md
  docs/index.md
Labels: feature freeze disallows change

#253 Change order of logo and heading
  docs/UserGuide.md
Labels: documentation

#257 Attempt to fix formatting issues
  docs/UserGuide.md
  docs/index.md
Labels: documentation bug

#246 Make error messages for `add` `edit` `delete` commands more specific
  docs/UserGuide.md
  src/main/java/seedu/masslinkers/commons/core/Messages.java
  src/main/java/seedu/masslinkers/logic/commands/EditCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModAddCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModDeleteCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModMarkCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModUnmarkCommand.java
  src/main/java/seedu/masslinkers/logic/parser/AddCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/AddInterestCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/DeleteInterestCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/ModCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/ParserUtil.java
  src/main/java/seedu/masslinkers/model/student/Mod.java
  src/test/java/seedu/masslinkers/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/ModCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/ParserUtilTest.java
Labels: bug fix

#256 Check documentation
  docs/UserGuide.md
Labels: documentation bug

#263 Make purple more visible
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
Labels: documentation

#269 Edit and shorten PPP to page limit
  docs/team/carriezhengjr.md
Labels: documentation

#270 Edit minor grammar issues in PPP
  docs/DeveloperGuide.md
  docs/team/carriezhengjr.md
Labels: documentation

#272 Fix GUI bug
  src/main/java/seedu/masslinkers/ui/StudentListPanel.java
Labels: bug fix
