Repository AY2223S1-CS2103T-T11-4/tp, pull requests merged in 2022-10, with the labels that each got.

#64 Modify Add and Edit + Testing to include GitHub Field
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/GitHub.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#67 Add find tag feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsTagPredicate.java
Labels: documentation, type.Story

#80 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#81 Add case-insensitive improvement to findTag and test cases
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/model/person/PersonContainsTagPredicate.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
Labels: type.Story

#83 Update User Guide: include all current and proposed features
  docs/UserGuide.md
Labels: documentation

#96 Add mod unmark command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ModUnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ModCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/ModUnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/ModCommandParserTest.java
Labels: core features

#99 Update the DG with design details
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModMarkActivityDiagram.puml
  docs/diagrams/ModMarkClassDiagram.puml
  docs/diagrams/ModMarkWithLoopActivityDiagram.puml
  docs/images/ModMarkActivityDiagram.png
  docs/images/ModMarkClassDiagram.png
  docs/images/ModMarkWithLoopActivityDiagram.png
Labels: documentation

#98 Mod Categorisation
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Mod.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/ModCard.java
  src/test/java/seedu/address/logic/commands/ModAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ModDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ModMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ModUnmarkCommandTest.java
  src/test/java/seedu/address/model/person/ModTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: core features

#103 Rename most other instances of tag to interest
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/interest/Interest.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInterest.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindInterestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: core features

#114 Reduce image size to fix lag
  src/main/resources/images/github.png
  src/main/resources/images/mail.png
  src/main/resources/images/phone.png
  src/main/resources/images/telegram.png
Labels: bug fix

#122 Update tests for `CommandResult` & update documentation
  docs/UserGuide.md
  docs/diagrams/ModCategorisationSequenceDiagram.puml
  docs/images/ModCategorisationSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindInterestCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ModFindCommandTest.java
Labels: documentation

#121 Update DG mod mark activity diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModMarkActivityDiagram.puml
  docs/diagrams/ModMarkWithLoopActivityDiagram.puml
  docs/images/ModMarkActivityDiagram.png
Labels: bug fix, documentation

#129 Mod mark UI
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddInterestCommand.java
  src/main/java/seedu/address/logic/commands/ModMarkCommand.java
  src/main/java/seedu/address/logic/parser/AddInterestCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModListPanel.java
  src/test/java/seedu/address/logic/commands/AddInterestCommandTest.java
Labels: bug fix

#131 Fix rescaling window size bug
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/book.png
  src/main/resources/images/person.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModListCard.fxml
  src/main/resources/view/ModListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/css/DarkTheme.css
  src/main/resources/view/css/Extensions.css
Labels: bug fix, ui

#133 Fix mod unmark bug and update mockup
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/ModUnmarkCommand.java
  src/main/java/seedu/address/ui/ModCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/css/DarkTheme.css
  src/main/resources/view/font/QTAncientOlive-Bold.otf
Labels: bug fix

#134 UG Changes: FAQ and Viewing a batchmate
  docs/UserGuide.md
Labels: documentation

#135 Sort mods by completion and name
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/ModComparator.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ModMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ModUnmarkCommandTest.java
  src/test/java/seedu/address/model/util/ModComparatorTest.java
Labels: enhancement

#117 Update FindInt in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindInterestActivityDiagram.puml
  docs/diagrams/FindInterestClassDiagram.puml
  docs/images/FindInterestActivityDiagram.png
  docs/images/FindInterestClassDiagram.png
Labels: documentation

#144 Bug Fix
  src/main/java/seedu/address/model/person/Mod.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/ModListPanel.java
  src/test/java/seedu/address/model/person/ModTest.java
Labels: bug fix

#145 Mod mark all
  src/main/java/seedu/address/logic/commands/ModCommand.java
  src/main/java/seedu/address/logic/commands/ModMarkAllCommand.java
  src/main/java/seedu/address/logic/commands/ModMarkCommand.java
  src/main/java/seedu/address/logic/parser/ModCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: core features

#147 Change mod mark all command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ModMarkAllCommand.java
  src/main/java/seedu/address/logic/parser/ModCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: core features

#148 Add tests for mod mark all
  src/main/java/seedu/address/logic/commands/ModMarkAllCommand.java
  src/test/java/seedu/address/logic/commands/ModDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ModMarkAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ModMarkCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: core features

#119 Add Interest Writeup in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddInterestRefSequenceDiagram.puml
  docs/diagrams/AddInterestSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddInterestRefSequenceDiagram.png
  docs/images/AddInterestSequenceDiagram.png
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#152 Edit bugs in mod mark all display message
  src/main/java/seedu/masslinkers/logic/commands/ModCommand.java
  src/main/java/seedu/masslinkers/ui/HelpWindow.java
Labels: bug fix

#159 Update carriezhengjr AboutUs
  docs/AboutUs.md
  docs/team/carriezhengjr.md
Labels: documentation

#160 Update Manual Testing Instructions
  docs/DeveloperGuide.md
Labels: documentation

#163 Update DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/tracing/FindUsages.png
  docs/images/tracing/searchResultsForExecuteMethod.png
  docs/index.md
  docs/tutorials/TracingCode.md
Labels: documentation

#164 Update DG product scope and value proposition
  docs/DeveloperGuide.md
  docs/diagrams/AddInterestRefSequenceDiagram.puml
  docs/diagrams/AddInterestSequenceDiagram.puml
  docs/images/AddInterestRefSequenceDiagram.png
  docs/images/AddInterestSequenceDiagram.png
Labels: documentation

#166 Bug Fix
  src/main/java/seedu/masslinkers/model/interest/Interest.java
  src/main/java/seedu/masslinkers/model/student/Name.java
  src/main/java/seedu/masslinkers/model/student/Student.java
  src/test/java/seedu/masslinkers/model/student/StudentTest.java
Labels: bug fix

#168 Update `StorageClassDiagram`
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#167 Increase Specificity of Error Messages
  docs/DeveloperGuide.md
  src/main/java/seedu/masslinkers/commons/core/Messages.java
  src/main/java/seedu/masslinkers/logic/commands/AddCommand.java
  src/main/java/seedu/masslinkers/logic/commands/AddInterestCommand.java
  src/main/java/seedu/masslinkers/logic/commands/DeleteCommand.java
  src/main/java/seedu/masslinkers/logic/commands/DeleteInterestCommand.java
  src/main/java/seedu/masslinkers/logic/commands/EditCommand.java
  src/main/java/seedu/masslinkers/logic/commands/FindCommand.java
  src/main/java/seedu/masslinkers/logic/commands/FindInterestCommand.java
  src/main/java/seedu/masslinkers/logic/commands/HelpCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ListCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModFindCommand.java
  src/main/java/seedu/masslinkers/logic/commands/ModMarkAllCommand.java
  src/main/java/seedu/masslinkers/logic/parser/AddCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/AddInterestCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/DeleteInterestCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/EditCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/FindCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/FindInterestCommandParser.java
  src/main/java/seedu/masslinkers/logic/parser/ModCommandParser.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/masslinkers/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/masslinkers/logic/parser/ModCommandParserTest.java
Labels: bug fix

#170 Fix Bug: Fix Broken Links and Student Uniqueness
  docs/DeveloperGuide.md
  docs/index.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/masslinkers/model/student/Student.java
  src/main/java/seedu/masslinkers/model/student/Telegram.java
  src/test/data/JsonSerializableMassLinkersTest/duplicateStudentMassLinkers.json
  src/test/java/seedu/masslinkers/model/MassLinkersTest.java
  src/test/java/seedu/masslinkers/model/student/UniqueStudentListTest.java
Labels: bug fix

#189 Fix some bugs in UG
  docs/UserGuide.md
  src/main/java/seedu/masslinkers/model/student/Mod.java
Labels: bug fix

#205 Fix documentation bugs in UG
  docs/UserGuide.md
Labels: bug fix, documentation

#208 Fix bugs from PED
  docs/UserGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation bug

#212 Fix more bugs and improve UG
  docs/UserGuide.md
  docs/images/UgModAddAfter.png
  docs/images/UgModAddBefore.png
  docs/images/UgModMarkAfter.png
  docs/images/UgModMarkBefore.png
  docs/images/UgViewModAfter.png
  docs/images/UgViewModBefore.png
  src/main/java/seedu/masslinkers/logic/commands/ModUnmarkCommand.java
  src/main/java/seedu/masslinkers/model/student/Mod.java
Labels: documentation bug

#215 Fix display bug in UG
  docs/UserGuide.md
Labels: documentation bug

#213 Bug Fixes
  docs/UserGuide.md
  docs/diagrams/ModCategorisationSequenceDiagram.puml
  docs/images/ModCategorisationSequenceDiagram.png
  src/main/java/seedu/masslinkers/model/student/Email.java
  src/main/java/seedu/masslinkers/model/student/GitHub.java
  src/main/java/seedu/masslinkers/model/student/Mod.java
  src/main/java/seedu/masslinkers/model/student/Telegram.java
Labels: bug fix

#223 Update PPP
  docs/UserGuide.md
  docs/team/jonasgwt.md
Labels: documentation

#226 Update PPP
  docs/AboutUs.md
  docs/team/elijahs67.md
  docs/team/johndoe.md
  docs/team/sltsheryl.md
Labels: documentation
